### ISSUE TITLE
vim-plug breaks repeating when using neocomplete with enable_smart_case

### ISSUE THREAD

**Issue by opennota** [junegunn/vim-plug#185]
The `.` (dot) command fails to repeat last change when using neocomplete plugin with `enable_smart_case = 1`.

Steps to reproduce:

1. Install neocomplete. Use the following `.vimrc` to plug it in:

    call plug#begin('~/.vim/plugged')
    Plug 'Shougo/neocomplete.vim'
    call plug#end()
    
    let g:neocomplete#enable_at_startup = 1
    " Use smartcase.
    let g:neocomplete#enable_smart_case = 1

2. Open [align.txt](http://pastebin.com/raw.php?i=9794YxEK).

3. Move to the first `case` keyword.

4. Press `cw` and type `align`.

5. Press `Esc`.

6. Move to the second `case`.

7. Press `.` (dot).

8. Repeat works incorrectly.

GIF screencast: http://i.imgur.com/L3YjYGL.gif

// When installed without vim-plug, neocomplete works fine.

**Comment by junegunn** [comment]
No, a plugin manager can't be the reason of the problem. Tried it w/o vim-plug and the problem persists:

```vim
" call plug#begin('~/.vim/plugged')
" Plug 'Shougo/neocomplete.vim'
" call plug#end()

" git clone --depth 1 git@github.com:Shougo/neocomplete.vim.git
set rtp+=neocomplete.vim

let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
```

**Comment by Shougo** [comment]
Yes.  It is not vim-plug problem.
It is neocomplete(Vim internal) problem.  It is already fixed in Vim 6.4.333.
https://github.com/Shougo/neocomplete.vim/issues/332

**Comment by junegunn** [comment]
@Shougo Hi Shougo, thanks for the confirmation!

**Comment by opennota** [comment]
@Shougo 
> It is already fixed in Vim 6.4.333.

**7**.4.333, you mean? I've updated vim to 7.4.622, and the bug is still there.

**Comment by Shougo** [comment]
Sorry.  It is Vim 7.4.633.
